### ISSUE TITLE
藤尾さんからのワーニングの連絡

### ISSUE THREAD

**Issue by ryutoiee** [toiee-lab/woocommerce-for-toieelab#21]

**Comment by ryutoiee** [comment]
「カスタムフィールド」の新規追加を押したときに

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Woocommerce_SimpleRestrictContent' does not have a method 'save_post_wcr' in /home/******/public_html/wp-includes/class-wp-hook.php on line 288

**Comment by toiee-kameda** [comment]
削除した機能の残りだった。  v0.9.6 で修正
